import { SVGs } from '@src/assets';
import { ExperienceProps } from '../types';
import { t } from 'i18next';

const { epiousionIt, diebold, going2, pts } = SVGs;

export const ExperiencesData: ExperienceProps[] = [
  {
    id: 1,
    company: 'home:CompanyI',
    ocupation: 'home:ExperienceI',
    logo: diebold,
    period: 'home:PeriodI',
    description: 'home:DescriptionI',
    techs: ['Hardware', 'Software'],
  },
  {
    id: 2,
    company: 'home:CompanyII',
    ocupation: 'home:ExperienceII',
    logo: going2,
    period: 'home:PeriodII',
    description: 'home:DescriptionII',
    techs: ['Scrum', 'Jira', 'Bitbucket', 'Figma'],
  },
  {
    id: 3,
    company: 'home:CompanyIII',
    ocupation: 'home:ExperienceIII',
    logo: epiousionIt,
    period: 'home:PeriodIII',
    description: 'home:DescriptionIII',
    techs: [
      'React',
      'NodeJs',
      'TypeScript',
      'HTML',
      'CSS',
      'StyledComponents',
      'RESTfulAPI',
      'PrismaORM',
      'SQL',
      'PostgreSQL',
      'Docker',
      'Git',
      'Scrum',
    ],
  },
  {
    id: 4,
    company: 'home:CompanyIV',
    ocupation: 'home:ExperienceIV',
    logo: epiousionIt,
    period: 'home:PeriodIV',
    description: 'home:DescriptionIV',
    techs: [
      'React',
      'NodeJs',
      'TypeScript',
      'HTML',
      'CSS',
      'StyledComponents',
      'RESTfulAPI',
      'PrismaORM',
      'SQL',
      'PostgreSQL',
      'Docker',
      'Git',
      'Scrum',
    ],
  },
  {
    id: 5,
    company: 'home:CompanyV',
    ocupation: 'home:ExperienceV',
    logo: pts,
    period: 'home:PeriodV',
    description: 'home:DescriptionV',
    techs: [
      'ReactNative',
      'TypeScript',
      'Firebase',
      'Git',
      'Figma',
      'Scrum',
      'Jira',
      'Bitbucket',
      'CSS',
      'HTML',
      'MySQL',
      'SQL',
      'StyledComponents',
      'RESTfulAPI',
    ],
  },
];
