import { SVGs } from '@src/assets';
import { ExperienceProps } from '../types';

const { freelancer, diebold, epiousion, pts } = SVGs;

export const ExperiencesData: ExperienceProps[] = [
  {
    id: 1,
    company: 'home:CompanyI',
    ocupation: 'home:ExperienceI',
    logo: freelancer,
    period: 'home:PeriodI',
    location: 'Sorocaba, SP',
    description: 'home:DescriptionI',
    techs: [
      'React',
      'NextJs',
      'ReactNative',
      'NodeJs',
      'Axios',
      'PrismaORM',
      'Express',
      'JWT',
      'TypeScript',
      'PostgreSQL',
      'Docker',
      'Git',
      'WordPress',
      'Cloudinary',
      'Webpack',
      'RESTfulAPI',
    ],
  },
  {
    id: 2,
    company: 'home:CompanyII',
    ocupation: 'home:ExperienceII',
    logo: diebold,
    period: 'home:PeriodII',
    location: 'Sorocaba, SP',
    type: 'home:hybrid',
    description: 'home:DescriptionII',
    techs: ['Hardware', 'Software'],
  },
  {
    id: 3,
    company: 'home:CompanyIII',
    ocupation: 'home:ExperienceIII',
    logo: epiousion,
    period: 'home:PeriodIII',
    location: 'Sorocaba, SP',
    type: 'home:hybrid',
    description: 'home:DescriptionIII',
    techs: [
      'React',
      'NodeJs',
      'TypeScript',
      'HTML',
      'CSS',
      'StyledComponents',
      'RESTfulAPI',
      'PrismaORM',
      'SQL',
      'PostgreSQL',
      'Docker',
      'Git',
      'Scrum',
    ],
  },
  {
    id: 5,
    company: 'home:CompanyIV',
    ocupation: 'home:ExperienceIV',
    logo: pts,
    period: 'home:PeriodIV',
    location: 'Sorocaba, SP',
    type: 'home:hybrid',
    description: 'home:DescriptionIV',
    techs: [
      'ReactNative',
      'TypeScript',
      'Firebase',
      'Git',
      'Figma',
      'Scrum',
      'Jira',
      'Bitbucket',
      'CSS',
      'HTML',
      'MySQL',
      'SQL',
      'StyledComponents',
      'RESTfulAPI',
    ],
  },
];
